-- NexCRM database schema entrypoint.
-- Run migrations with:
--
--   npm run db:migrate
--
-- The full production schema starts at:
--
--   db/migrations/001_initial_relational_schema.sql
--
-- The previous MVP `nexcrm_state` JSONB table is intentionally not created here.
